-- @CREATE_PRODUCT_QUERY
CREATE TABLE IF NOT EXISTS PRODUCT
(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NAME           TEXT    NOT NULL,
PRICE          INT     NOT NULL);

-- @INSERT_PRODUCT_QUERY
INSERT INTO PRODUCT (NAME, PRICE) VALUES ("{{name}}", {{price}});

-- @SELECT_PRODUCT_QUERY
SELECT * FROM PRODUCT;

-- @SELECT_MAX_PRODUCT_QUERY
SELECT * FROM PRODUCT ORDER BY PRICE DESC LIMIT 1;

-- @SELECT_MIN_PRODUCT_QUERY
SELECT * FROM PRODUCT ORDER BY PRICE LIMIT 1;

-- @SELECT_SUM_PRODUCT_QUERY
SELECT SUM(price) FROM PRODUCT;

-- @SELECT_COUNT_PRODUCT_QUERY
SELECT COUNT(*) FROM PRODUCT;

-- @CLEAR_PRODUCT_QUERY
DELETE FROM PRODUCT;